swagger: "2.0"

info:
  version: 1.0.0
  title: Transformations Service
  description: This API allows to perform operations in a table matrix.
schemes:
  - http
host: localhost:3005
basePath: /Heavy_Ops/v1

paths:
  /HeavyOps/{UserID}/{DatasetID}/{OperID}/:
    post:
      tags:
        - Transformation
      description: Calculate transformation of a dataset
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
       - name: UserID
         in: path
         required: true
         type: string
       - name: DatasetID
         in: path
         required: true
         type: string
       - name: OperID
         in: path
         required: true
         type: string
       - name: datasetV
         in: query
         required: false
         description: Dataset values for the operation. 
         type: string
       - name: MyRef
         in: query
         required: true
         description: Reference for callback after operation finishes
         type: string
       - name: URLCallback
         in: query
         required: true
         description: URL for callback after operation finishes
         type: string
      responses:
        202:
          description: Accepted.
        400:
          description: Bad request. Check the definition documentation.